// <auto-generated />
using System;
using Labb2._0_BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2._0_BlazorApp.Migrations
{
    [DbContext(typeof(YourDbContext))]
    partial class YourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AuthorId")
                        .HasName("PK__Author__70DAFC142BA7F681");

                    b.ToTable("Author", (string)null);
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Book", b =>
                {
                    b.Property<string>("Isbn13")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ISBN13");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Languege")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnName("PublisherID");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Isbn13")
                        .HasName("PK__Books__3BF79E038D206177");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.BookStockInStore", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnName("InventoryID");

                    b.Property<string>("Isbn13")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ISBN13");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("StoreID");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ToTable((string)null);

                    b.ToView("BookStockInStore", (string)null);
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("StoreID");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64B82C3B084D");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("EmployeeEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeLastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EmployeeStore")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04FF1573B60D0");

                    b.HasIndex("EmployeeStore");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnName("InventoryID");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("InventoryId", "Isbn")
                        .HasName("PK__Inventor__51BA35BD57CD28AC");

                    b.HasIndex("Isbn");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAF39C14F24");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PublisherID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("PublisherName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PublisherId")
                        .HasName("PK__Publishe__4C657E4B7223CCDB");

                    b.ToTable("Publisher", (string)null);
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StoreID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<string>("StoreNamn")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Storedress")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("StoreId")
                        .HasName("PK__Stores__3B82F0E11C07379A");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Book", b =>
                {
                    b.HasOne("Labb2._0_BlazorApp.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK__Books__AuthorID__36B12243");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Employee", b =>
                {
                    b.HasOne("Labb2._0_BlazorApp.Models.Store", "EmployeeStoreNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeStore")
                        .HasConstraintName("FK__Employee__Employ__45F365D3");

                    b.Navigation("EmployeeStoreNavigation");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Inventory", b =>
                {
                    b.HasOne("Labb2._0_BlazorApp.Models.Store", "InventoryNavigation")
                        .WithMany("Inventories")
                        .HasForeignKey("InventoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Inven__3B75D760");

                    b.HasOne("Labb2._0_BlazorApp.Models.Book", "IsbnNavigation")
                        .WithMany("Inventories")
                        .HasForeignKey("Isbn")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__ISBN__3C69FB99");

                    b.Navigation("InventoryNavigation");

                    b.Navigation("IsbnNavigation");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Order", b =>
                {
                    b.HasOne("Labb2._0_BlazorApp.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Orders__Customer__412EB0B6");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Book", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Labb2._0_BlazorApp.Models.Store", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
